In [11]:
import nltk
nltk.data.path.append("/home/master/datasets")
import numpy as np
import pandas as pd
from nltk.corpus import movie_reviews
import sklearn
from sklearn.pipeline import make_pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import make_scorer, roc_auc_score
from sklearn.model_selection import cross_val_score
import pickle

In [3]:
negids = movie_reviews.fileids('neg')
posids = movie_reviews.fileids('pos')
negfeats = [movie_reviews.words(fileids=[f]) for f in negids]
posfeats = [movie_reviews.words(fileids=[f]) for f in posids]
X = [*negfeats, *posfeats]
X = [" ".join(list(x)) for x in X]
y = [0]*len(negfeats)+[1]*len(posfeats)

In [7]:
model = make_pipeline(TfidfVectorizer(stop_words=nltk.corpus.stopwords.words('english')), GradientBoostingClassifier())


In [10]:
cross_val_score(model, X, y)

array([0.79  , 0.7975, 0.8075, 0.7875, 0.83  ])

In [17]:
model.fit(X, y)

Pipeline(steps=[('tfidfvectorizer',
                 TfidfVectorizer(stop_words=['i', 'me', 'my', 'myself', 'we',
                                             'our', 'ours', 'ourselves', 'you',
                                             "you're", "you've", "you'll",
                                             "you'd", 'your', 'yours',
                                             'yourself', 'yourselves', 'he',
                                             'him', 'his', 'himself', 'she',
                                             "she's", 'her', 'hers', 'herself',
                                             'it', "it's", 'its', 'itself', ...])),
                ('gradientboostingclassifier', GradientBoostingClassifier())])

In [22]:
with open("SklearnModel.pkl", "wb") as fout:
    pickle.dump(model, fout)

In [20]:
model.predict(["bad ugly horrible"])

array([0])

In [21]:
model.predict(["nice great awesome"])

array([1])

In [23]:
model.predict_proba(["nice great awesome"])

array([[0.26313356, 0.73686644]])